name: 'Daily Perf Improver Build Steps'
description: 'Set up environment for performance testing and development work in dateutil'
author: 'Daily Perf Improver'

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        allow-prereleases: true
        
    - name: Install system dependencies
      shell: bash
      run: |
        # Install system packages that may be needed for performance work
        sudo apt-get update -qq
        sudo apt-get install -y build-essential
        
    - name: Upgrade pip and install build tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        
    - name: Install package in development mode
      shell: bash
      run: |
        python -m pip install -e .
        
    - name: Install development dependencies
      shell: bash
      run: |
        python -m pip install -r requirements-dev.txt
        
    - name: Install performance testing tools
      shell: bash
      run: |
        python -m pip install pytest-benchmark memory-profiler line-profiler
        
    - name: Update timezone info
      shell: bash
      run: |
        # Run updatezinfo.py as done in CI to ensure timezone data is current
        python updatezinfo.py
        
    - name: Run basic functionality test
      shell: bash
      run: |
        python -c "import dateutil; import dateutil.parser; import dateutil.rrule; import dateutil.tz; print('dateutil modules imported successfully')"
        
    - name: Verify test environment
      shell: bash
      run: |
        # Quick test to ensure environment is working
        python -m pytest tests/test_imports.py -v