name: 'Coverage Steps'
description: 'Run tests and generate coverage reports for dateutil'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install tox
        
    - name: Install package
      shell: bash  
      run: |
        pip install -e .
        
    - name: Run tests with coverage
      shell: bash
      run: |
        python -m pytest tests/ --cov=dateutil --cov-report=xml --cov-report=html --cov-report=term-missing
        
    - name: Generate detailed coverage report
      shell: bash
      run: |
        python -m coverage report --show-missing > coverage-report.txt
        python -m coverage html
        
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v3
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
          coverage-report.txt
        retention-days: 30