name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  pypi-hosts: "pypi.python.org pypi.org files.pythonhosted.org"

jobs:
  test:
    strategy:
      matrix:
        python-version: [
          # "3.8",
          # "3.9",
          # "3.10",
          # "3.11",
          "3.12",
          # "3.13",
          # "pypy-2.7",
          # "pypy-3.8",
        ]
        os:
        - ubuntu-latest
        #os: [ubuntu-latest, windows-latest, macos-latest]
        # include:
        #   # Older versions (<=3.7) are included separately since they need
        #   # special handling (using an older os or a container)
        #   - os: "macos-13"
        #     python-version: "3.5"
        #   - os: "macos-13"
        #     python-version: "3.6"
        #   - os: "macos-13"
        #     python-version: "3.7"
        #   - os: "windows-latest"
        #     python-version: "3.5"
        #   - os: "windows-latest"
        #     python-version: "3.6"
        #   - os: "windows-latest"
        #     python-version: "3.7"
        #   - os: "ubuntu-latest"
        #     python-version: "2.7"
        #     use-container: true
        #   - os: "ubuntu-latest"
        #     python-version: "3.5"
        #     use-container: true
        #   - os: "ubuntu-latest"
        #     python-version: "3.6"
        #     use-container: true
        #   - os: "ubuntu-latest"
        #     python-version: "3.7"
        #     use-container: true
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.use-container && format('python:{0}', matrix.python-version) || '' }}
    env:
      TOXENV: py
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - if: ${{ !matrix.use-container }}
        name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }} (non-containers)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
        env:
          PIP_TRUSTED_HOST: ${{ contains(fromJson('["3.5"]'), matrix.python-version) && env.pypi-hosts || '' }}
      - name: Install dependencies
        run: python -m pip install -U tox six
      - name: Install zic (Windows)
        run: |
          curl https://get.enterprisedb.com/postgresql/postgresql-9.5.21-2-windows-x64-binaries.zip --output $env:GITHUB_WORKSPACE\postgresql9.5.21.zip
          unzip -oq $env:GITHUB_WORKSPACE\postgresql9.5.21.zip -d .postgresql
        if: runner.os == 'Windows'
      - name: Run updatezinfo.py (Windows)
        run: |
          $env:Path += ";$env:GITHUB_WORKSPACE\.postgresql\pgsql\bin"
          ci_tools/retry.bat python updatezinfo.py
        if: runner.os == 'Windows'
      - name: Run updatezinfo.py (Unix)
        run: ./ci_tools/retry.sh python updatezinfo.py
        if: runner.os != 'Windows'
      - name: Run tox
        run: python -m tox
      - name: Generate coverage.xml
        run: python -m tox -e coverage
      - name: Report coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./.tox/coverage.xml
          name: ${{ matrix.os }}:${{ matrix.python-version }}
          fail_ci_if_error: false
          # codecov/codecov-action@v3 needs v0.7.3 to work on (intel) macos-13
          # See https://github.com/codecov/codecov-action/issues/1549
          version: ${{ matrix.os == 'macos-13' && 'v0.7.3' || 'latest' }}

